workdir: .

max_threads_per_rule: 1

dcc_lab: anshul-kundaje
dcc_award: UM1HG009442
dcc_mode: prod

chrom_sizes: https://www.encodeproject.org/files/GRCh38_EBV.chrom.sizes/@@download/GRCh38_EBV.chrom.sizes.tsv
blacklist: https://www.encodeproject.org/files/ENCFF356LFX/@@download/ENCFF356LFX.bed.gz

bc_wl_rna: http://mitra.stanford.edu/kundaje/atwang/rna_whitelists/737K-arc-v1.txt.gz
bc_wl_atac: http://mitra.stanford.edu/kundaje/atwang/atac_whitelists/737K-arc-v1.txt.gz

amulet_repo: https://github.com/UcarLab/AMULET.git
amulet_repo_lowmem: https://github.com/austintwang/AMULET.git

amulet_fdr: 0.01

archr_seed: 8757647
archr_min_frags: 5000
archr_min_tss_enr: 5

bsgenome: http://mitra.stanford.edu/kundaje/surag/ENCODE_scatac/BSgenome/BSgenome.Hsapiens.ENCODE.GRCh38/BSgenome.Hsapiens.ENCODE.GRCh38_1.0.0.tar.gz
bsgenome_name: BSgenome.Hsapiens.ENCODE.GRCh38
archr_gene_anno: https://github.com/GreenleafLab/ArchR/raw/v1.0.1/data/geneAnnoHg38.rda
gene_anno_name: geneAnnoHg38

seurat_seed: 2398756
seurat_min_count: 1000
seurat_max_pct_mito: 5

pseudorep_split_frac: 0.5

rna_cluster_resolution: 1.

# rna_ref_kramann_data: http://mitra.stanford.edu/kundaje/atwang/encode_scatac_manual/cardiac_refs/kramann/local.rds
rna_ref_kramann:
  unified: https://zenodo.org/record/6578047/files/snRNA-seq-submission.h5ad?download=1
  subtypes:
    Cardiomyocyte: https://zenodo.org/record/7098004/files/Cardiomyocyte_snRNA_snATAC.Rds?download=1
    Endothelial: https://zenodo.org/record/7098004/files/Endothelial_snRNA_snATAC.Rds?download=1
    Lymphoid: https://zenodo.org/record/7098004/files/Lymphoid_snRNA_snATAC.Rds?download=1
    Myeloid: https://zenodo.org/record/7098004/files/Myeloid_snRNA_snATAC.Rds?download=1
    Neuronal: https://zenodo.org/record/7098004/files/Neuronal_snRNA_snATAC.Rds?download=1
    Pericyte: https://zenodo.org/record/7098004/files/Pericyte_snRNA_snATAC.Rds?download=1
    vSMCs: https://zenodo.org/record/7098004/files/vSMCs_snRNA_snATAC.Rds?download=1 

# cell_type_original
# annotation
  

rna_ref_ellinor:
  mat: http://mitra.stanford.edu/kundaje/atwang/encode_scatac_manual/cardiac_refs/ellinor/SCP1303/expression/614a0209771a5b0d7f03370f/DCM_HCM_Expression_Matrix_V1.mtx.gz
  features: http://mitra.stanford.edu/kundaje/atwang/encode_scatac_manual/cardiac_refs/ellinor/SCP1303/expression/614a0209771a5b0d7f03370f/DCM_HCM_Expression_Matrix_genes_norm_V1.tsv.gz
  cells: http://mitra.stanford.edu/kundaje/atwang/encode_scatac_manual/cardiac_refs/ellinor/SCP1303/expression/614a0209771a5b0d7f03370f/DCM_HCM_Expression_Matrix_barcodes_norm_V1.tsv.gz
  mat_raw: http://mitra.stanford.edu/kundaje/atwang/encode_scatac_manual/cardiac_refs/ellinor/SCP1303/expression/614a0209771a5b0d7f033712/DCM_HCM_Expression_Matrix_raw_counts_V1.mtx.gz
  features_raw: http://mitra.stanford.edu/kundaje/atwang/encode_scatac_manual/cardiac_refs/ellinor/SCP1303/expression/614a0209771a5b0d7f033712/DCM_HCM_Expression_Matrix_genes_V1.tsv.gz
  cells_raw: http://mitra.stanford.edu/kundaje/atwang/encode_scatac_manual/cardiac_refs/ellinor/SCP1303/expression/614a0209771a5b0d7f033712/DCM_HCM_Expression_Matrix_barcodes_V1.tsv.gz
  metadata: http://mitra.stanford.edu/kundaje/atwang/encode_scatac_manual/cardiac_refs/ellinor/SCP1303/metadata/DCM_HCM_MetaData_V1.txt.gz

rna_ref_teichmann_data: https://cellgeni.cog.sanger.ac.uk/heartcellatlas/data/global_raw.h5ad

azimuth_ref: http://seurat.nygenome.org/src/contrib/heartref.SeuratData_1.0.0.tar.gz

doublet_formation_rate: 0.06

gtf: https://www.encodeproject.org/files/ENCFF159KBI/@@download/ENCFF159KBI.gtf.gz

seq_emb_dir: /mnt/lab_data3/salil512/adult_heart/post_analysis/embeddings